name: Run Terraform Checks
on:
  pull_request:
jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      - uses: nationalarchives/tdr-github-actions/.github/actions/run-git-secrets@f318ce8a5d99c08b1235663f97fdb1b35844674e
      - uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@e7b57a3bdf7863c951cd203101c6d566986376e3
        if: failure()
        with:
          message: ":warning: Secrets found in repository da-terraform-modules"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check --recursive
